v0.3.4 (#2)
* mitigation: Mitigate AE1 bug

AE1 mistakenly passes in `1` as an ASM api version when it uses
`SignatureVisitor`. This is valid in ASM4 because it never checks if the
Opcode is valid, this is fixed in ASM5, which we override ASM4 with due
to compatibility issues with the Java 8 JRE we use

* fix: kilt crashing due to how caciocavallo17 is loaded

Fixes https://github.com/KiltMC/Kilt/issues/230 by using a javaagent
instead of a custom classloader

Uses
https://github.com/AngelAuraMC/caciocavallo17/actions/runs/20203346684

* fix: PojavLauncher -> Amethyst in License note

Signed-off-by: blryface <me@blurry.gay>

* fix: Grab JRE from any completed run

This stops it from failing if we only have cancelled or errored runs but
still have android jre artifacts

* add: Sodium warning

Should now let sodium launch but display a warning

* fix: negative numbers not being typable

* add: Delete Sodium and dependents button in Sodium warning

* rework: Sodium warning message

Now makes you wait some time to properly read everything.

* Add functionality to import modpacks

Lets you import modpacks from mrpacks and zips

* fix: Fix mimetype issues with stock android not matching .mrpack

We want to be able to grey out files that are not .zip or .mrpack  so
people can have an easier chance of seeing their modpacks. To do this,
we match the `application/x-modrinth-modpack+zip` and `application/zip`
mimetypes as prescribed in the Modrinth documentation
https://support.modrinth.com/en/articles/8802351-modrinth-modpack-format-mrpack.

Stock android does not have `application/x-modrinth-modpack+zip`. OEM
vendors seem to include this in their ROMs, possibly from just using
https://gitlab.freedesktop.org/xdg/shared-mime-info as part of where
they source their additional mimetypes from.

There's a tendency for Android 12 and below to not have the
`application/x-modrinth-modpack+zip` mimetype, likely due to the
addition of it being relatively recent, so we have to account for that
by also adding `application/octet-stream`.

We cannot only have `application/octet-stream` or else it fails to match
.mrpack in systems that have `application/x-modrinth-modpack+zip`.

Sadly there seems to be no reliable way to check whether or the the ROM
has the `application/x-modrinth-modpack+zip` mimetype so we just match
it along with `application/octet-stream` to cover our bases.

* fix: Properly show error for incorrect file

It was crashing the launcher before, now it shows it in a box

* fix: workaround android 7 crash with Hex.encodeHexString

For some reason it keeps trying to use the system apache commons instead
of the one in the app, and because that one is really old, this method
is missing so it crashes.

Crash report
 - Time: 26-Dec-2025 6:46:49 PM
 - Device: lineage_Hol-U19 Hol-U19
 - Android version: 7.1.2
 - Crash stack trace:
 - Launcher version:
amethyst-legacy-20251226-c798f65-feat/import-modpack
java.lang.NoSuchMethodError: No static method
encodeHexString([B)Ljava/lang/String; in class
Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration
of 'org.apache.commons.codec.binary.Hex' appears in
/system/framework/org.apache.http.legacy.boot.jar)

* fix: Fix crash report text from Pojav to Amethyst

the rebranding should really have been done far earlier. oh well, we're
gonna roll with it

* fix: Neoforge not creating instances on modpack install

* fix: Neoforge not installing on modpack install

Also reworks the neoforge profile install to use neoforge maven
https://maven.neoforged.net/releases/net/neoforged/neoforge/maven-metadata.xml

This is away from using prism's jsons
https://meta.prismlauncher.org/v1/net.neoforged/index.json

This is because prism still has 1.20.1 listed, and we can't really run
those. We could have ran with prism for the profile select but that
would be even more confusing.

* refactor: NeoForgeDownloadTask to one constructor

Simplifies to one constructor. We don't need to copy the approach of
forge because neoforge integrates the minecraft version into their
version scheme, thus we have no use for the minecraft version provided
to us.

* fix: OneUI rendering issues with Turnip by turning off UBWC

I believe we don't have any reason to be concerned about RAM bandwidth
limitations. This isn't the N64, and Minecraft is a pixelated game.

* add: Sodium warning to log

* fix: Update renderer autoselect

New behavior is as follows.
If below 1.17, use the GL4ES based renderer.
If below 1.17 and modded, use the Mesa renderer (Zink in this case).
If above 1.17 and/or modded, use MobileGlues.

* fix: JVM arguments getting newlines inside it when pasting

When you paste a string with newlines in it, it literally puts newlines
here, then parsing it goes all wonky because of that.

Never trust user input

* v0.3.4

* Add public beta release workflow and improve reinstall

- Introduces a new GitHub Actions workflow for public beta releases, including APK signing and changelog generation.
- Updates the README with download, installation, and beta information.
- Refactors the game reinstall logic to only remove and unpack resource folders instead of deleting the entire game directory, and adds a new method to unpack game resources without re-downloading.
- Improves user feedback and error handling during the reinstall process.

* Update release.yml

* Update release.yml

* Revert "Merge remote-tracking branch 'upstream/v3_openjdk' into v3_openjdk"

This reverts commit ce4e9ab7075331793dc1d92914cb1a2f67e7cc0a, reversing
changes made to b440eed18c687300fceec1a1fa0fc7f892ca6976.

* Update AsyncAssetManager.java

* Update JavaGUILauncherActivity.java

---------

Signed-off-by: blryface <me@blurry.gay>
Signed-off-by: SirDank <52797753+SirDank@users.noreply.github.com>
Co-authored-by: alexytomi <60690056+alexytomi@users.noreply.github.com>
Co-authored-by: blryface <me@blurry.gay>